// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetCore.Fundamentals.OIC.Data.Entities
{
    public partial class Attendee
    {
        public int AttendeeId { get; set; }
        public int ConferenceId { get; set; }
        public string Name { get; set; }

        public virtual Conference Conference { get; set; }
    }
}