// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetCore.Fundamentals.OIC.Data.Entities
{
    public partial class Conference
    {
        public Conference()
        {
            Attendees = new HashSet<Attendee>();
            Proposals = new HashSet<Proposal>();
        }

        public int ConferenceId { get; set; }
        public string Name { get; set; }
        public DateTime Start { get; set; }
        public string Location { get; set; }

        public virtual ICollection<Attendee> Attendees { get; set; }
        public virtual ICollection<Proposal> Proposals { get; set; }
    }
}