// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetCore.Fundamentals.OIC.Data.Entities
{
    public partial class Proposal
    {
        public int ProposalId { get; set; }
        public int ConferenceId { get; set; }
        public string Speaker { get; set; }
        public string Title { get; set; }
        public bool Approved { get; set; }

        public virtual Conference Conference { get; set; }
    }
}