// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using NetCore.Fundamentals.OIC.Data.Entities;
using System;
using Microsoft.EntityFrameworkCore;

namespace NetCore.Fundamentals.OIC.Data.Context
{
    public partial class NetcoreFundamentalsOICContext : DbContext
    {
        public NetcoreFundamentalsOICContext()
        {
        }

        public NetcoreFundamentalsOICContext(DbContextOptions<NetcoreFundamentalsOICContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Attendee> Attendees { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<Proposal> Proposals { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Attendee>(entity =>
            {
                entity.ToTable("Attendee");

                entity.HasIndex(e => e.ConferenceId);

                entity.Property(e => e.Name).HasMaxLength(250);

                entity.HasOne(d => d.Conference)
                    .WithMany(p => p.Attendees)
                    .HasForeignKey(d => d.ConferenceId)
                    .HasConstraintName("FK_Attendee_Conference");
            });

            modelBuilder.Entity<Conference>(entity =>
            {
                entity.ToTable("Conference");

                entity.Property(e => e.Location).HasMaxLength(250);

                entity.Property(e => e.Name).HasMaxLength(250);
            });

            modelBuilder.Entity<Proposal>(entity =>
            {
                entity.ToTable("Proposal");

                entity.HasIndex(e => e.ConferenceId);

                entity.HasOne(d => d.Conference)
                    .WithMany(p => p.Proposals)
                    .HasForeignKey(d => d.ConferenceId)
                    .HasConstraintName("FK_Proposal_Conference");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}