//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxy.EF.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentarioHistoria
    {
        public int ComentarioId { get; set; }
        public int PostId { get; set; }
        public string Contenido { get; set; }
        public int UsuarioIdPropietario { get; set; }
        public int UsuarioIdCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioIdActualizacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public System.DateTime SysStartTime { get; set; }
        public System.DateTime SysEndTime { get; set; }
    }
}
